@echo off
setlocal enabledelayedexpansion

REM NEP 2020 Complete Pipeline Execution Script for Windows
REM Runs all three engines in sequence with proper error handling

echo ==========================================
echo NEP 2020 COMPLETE TIMETABLE PIPELINE
echo Industry-Level Production System
echo ==========================================

REM Check arguments
if "%~1"=="" (
    echo Usage: %0 ^<csv_input_directory^>
    echo Example: %0 ../sample_data/
    exit /b 1
)

set CSV_DIR=%1
for /f "tokens=1-5 delims=/ " %%A in ('date /t') do set CURRENT_DATE=%%C%%A%%B
for /f "tokens=1-2 delims=: " %%A in ('time /t') do set CURRENT_TIME=%%A%%B
set CURRENT_TIME=%CURRENT_TIME: =0%
set TIMESTAMP=%CURRENT_DATE%_%CURRENT_TIME%

echo 📂 Input CSV Directory: %CSV_DIR%
echo ⏰ Pipeline Start Time: %date% %time%
echo 🔖 Timestamp: %TIMESTAMP%
echo.

REM Stage 1: CSV Processing Engine
echo 🚀 STAGE 1: CSV PROCESSING ^& DATA VALIDATION
echo ----------------------------------------
cd engines
python csv_processing_engine.py "%CSV_DIR%"
if errorlevel 1 (
    echo ❌ ERROR: CSV Processing Engine failed
    exit /b 1
)

REM Find the generated optimization matrix
set MATRIX_FILE=
for /f "delims=" %%i in ('dir /b /o-d "..\csv_processing_output\optimization_matrix_*.json" 2^>nul') do (
    if not defined MATRIX_FILE set MATRIX_FILE=..\csv_processing_output\%%i
)

if not defined MATRIX_FILE (
    echo ❌ ERROR: No optimization matrix generated by CSV engine
    exit /b 1
)

echo ✅ Generated: %MATRIX_FILE%
echo.

REM Stage 2: Solver Engine
echo 🧠 STAGE 2: SOLVER SELECTION ^& EXECUTION
echo ----------------------------------------
python solver_engine_prototype.py "%MATRIX_FILE%"
if errorlevel 1 (
    echo ❌ ERROR: Solver Engine failed
    exit /b 1
)

REM Find the generated timetable
set TIMETABLE_FILE=
for /f "delims=" %%i in ('dir /b /o-d "..\solver_output	imetable_*.csv" 2^>nul') do (
    if not defined TIMETABLE_FILE set TIMETABLE_FILE=..\solver_output\%%i
)

if not defined TIMETABLE_FILE (
    echo ❌ ERROR: No timetable generated by solver engine
    exit /b 1
)

echo ✅ Generated: %TIMETABLE_FILE%
echo.

REM Stage 3: Validation & Formatting Engine
echo ✅ STAGE 3: VALIDATION ^& FORMATTING
echo ----------------------------------------
python validation_engine_prototype.py "%TIMETABLE_FILE%" "%MATRIX_FILE%"
if errorlevel 1 (
    echo ❌ ERROR: Validation Engine failed
    exit /b 1
)

REM Find the final matrix
set FINAL_MATRIX=
for /f "delims=" %%i in ('dir /b /o-d "..alidation_outputinal_timetable_matrix_*.csv" 2^>nul') do (
    if not defined FINAL_MATRIX set FINAL_MATRIX=..alidation_output\%%i
)

if not defined FINAL_MATRIX (
    echo ❌ ERROR: No final matrix generated by validation engine
    exit /b 1
)

echo ✅ Generated: %FINAL_MATRIX%
echo.

REM Summary
echo 🎉 PIPELINE COMPLETED SUCCESSFULLY!
echo ==========================================
echo 📁 PRIMARY OUTPUT: %FINAL_MATRIX%
echo ⏰ Pipeline End Time: %date% %time%

REM List all generated files
echo.
echo 📋 ALL GENERATED FILES:
echo CSV Processing Outputs:
if exist "..\csv_processing_output" (
    for /f "delims=" %%i in ('dir /b "..\csv_processing_output\*%TIMESTAMP%*" 2^>nul') do echo ..\csv_processing_output\%%i
    for /f "tokens=1-3 delims=/ " %%A in ('date /t') do (
        for /f "delims=" %%i in ('dir /b "..\csv_processing_output\*%%C%%A%%B*" 2^>nul') do echo ..\csv_processing_output\%%i
    )
)

echo.
echo Solver Outputs:
if exist "..\solver_output" (
    for /f "delims=" %%i in ('dir /b "..\solver_output\*%TIMESTAMP%*" 2^>nul') do echo ..\solver_output\%%i
    for /f "tokens=1-3 delims=/ " %%A in ('date /t') do (
        for /f "delims=" %%i in ('dir /b "..\solver_output\*%%C%%A%%B*" 2^>nul') do echo ..\solver_output\%%i
    )
)

echo.
echo Validation Outputs:
if exist "..alidation_output" (
    for /f "delims=" %%i in ('dir /b "..alidation_output\*%TIMESTAMP%*" 2^>nul') do echo ..alidation_output\%%i
    for /f "tokens=1-3 delims=/ " %%A in ('date /t') do (
        for /f "delims=" %%i in ('dir /b "..alidation_output\*%%C%%A%%B*" 2^>nul') do echo ..alidation_output\%%i
    )
)

echo.
echo Audit Logs:
if exist "..\csv_processing_audit_logs" (
    for /f "delims=" %%i in ('dir /b "..\csv_processing_audit_logs\*%TIMESTAMP%*" 2^>nul') do echo ..\csv_processing_audit_logs\%%i
)
if exist "..\solver_audit_logs" (
    for /f "delims=" %%i in ('dir /b "..\solver_audit_logs\*%TIMESTAMP%*" 2^>nul') do echo ..\solver_audit_logs\%%i
)
if exist "..alidation_audit_logs" (
    for /f "delims=" %%i in ('dir /b "..alidation_audit_logs\*%TIMESTAMP%*" 2^>nul') do echo ..alidation_audit_logs\%%i
)

echo.
echo 🚀 READY FOR DEPLOYMENT TO GOVERNMENT INSTITUTIONS!
echo ==========================================

endlocal
