#!/bin/bash
# NEP 2020 Complete Pipeline Execution Script
# Runs all three engines in sequence with proper error handling

set -e  # Exit on any error

echo "=========================================="
echo "NEP 2020 COMPLETE TIMETABLE PIPELINE"
echo "Industry-Level Production System"
echo "=========================================="

# Check arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <csv_data_directory>"
    echo "Example: $0 ../sample_data/"
    exit 1
fi

CSV_DIR="$1"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

echo "📂 Input CSV Directory: $CSV_DIR"
echo "⏰ Pipeline Start Time: $(date)"
echo "🔖 Timestamp: $TIMESTAMP"
echo ""

# Stage 1: CSV Processing Engine
echo "🚀 STAGE 1: CSV PROCESSING & DATA VALIDATION"
echo "----------------------------------------"
cd engines
python csv_processing_engine.py "$CSV_DIR"

# Find the generated optimization matrix
MATRIX_FILE=$(ls -t ../csv_processing_output/optimization_matrix_*.json 2>/dev/null | head -1)
if [ -z "$MATRIX_FILE" ]; then
    echo "❌ ERROR: No optimization matrix generated by CSV engine"
    exit 1
fi
echo "✅ Generated: $MATRIX_FILE"
echo ""

# Stage 2: Solver Engine
echo "🧠 STAGE 2: SOLVER SELECTION & EXECUTION"
echo "----------------------------------------"
python solver_engine_prototype.py "$MATRIX_FILE"

# Find the generated timetable
TIMETABLE_FILE=$(ls -t ../solver_output/timetable_*.csv 2>/dev/null | head -1)
if [ -z "$TIMETABLE_FILE" ]; then
    echo "❌ ERROR: No timetable generated by solver engine"
    exit 1
fi
echo "✅ Generated: $TIMETABLE_FILE"
echo ""

# Stage 3: Validation & Formatting Engine  
echo "✅ STAGE 3: VALIDATION & FORMATTING"
echo "----------------------------------------"
python validation_engine_prototype.py "$TIMETABLE_FILE" "$MATRIX_FILE"

# Find the final matrix
FINAL_MATRIX=$(ls -t ../validation_output/final_timetable_matrix_*.csv 2>/dev/null | head -1)
if [ -z "$FINAL_MATRIX" ]; then
    echo "❌ ERROR: No final matrix generated by validation engine"
    exit 1
fi
echo "✅ Generated: $FINAL_MATRIX"
echo ""

# Summary
echo "🎉 PIPELINE COMPLETED SUCCESSFULLY!"
echo "=========================================="
echo "📁 PRIMARY OUTPUT: $FINAL_MATRIX"
echo "⏰ Pipeline End Time: $(date)"

# List all generated files
echo ""
echo "📋 ALL GENERATED FILES:"
echo "CSV Processing Outputs:"
find ../csv_processing_output/ -name "*$TIMESTAMP*" -o -name "*$(date +%Y%m%d)*" 2>/dev/null | sort
echo ""
echo "Solver Outputs:"
find ../solver_output/ -name "*$TIMESTAMP*" -o -name "*$(date +%Y%m%d)*" 2>/dev/null | sort
echo ""
echo "Validation Outputs:"
find ../validation_output/ -name "*$TIMESTAMP*" -o -name "*$(date +%Y%m%d)*" 2>/dev/null | sort
echo ""
echo "Audit Logs:"
find ../*audit_logs/ -name "*$TIMESTAMP*" -o -name "*$(date +%Y%m%d)*" 2>/dev/null | sort

echo ""
echo "🚀 READY FOR DEPLOYMENT TO GOVERNMENT INSTITUTIONS!"
echo "=========================================="
